name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-cache-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-maven-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v1
        with:
          name: smithereen-jar-with-dependencies.jar
          path: target/smithereen-jar-with-dependencies.jar
