name: Java CI

on:
    push:
        branches:
            - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            src/main/web/node_modules
            target/node
          key: ${{ runner.os }}-build-cache-maven
      - name: Build with Maven
        run: mvn -B package
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v1
        with:
          name: smithereen-jar-with-dependencies.jar
          path: target/smithereen-jar-with-dependencies.jar
